auth_enabled: false
server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  aws:
    s3: http://minioadmin:minioadmin@minio:9000
    endpoint: http://minio:9000
    s3forcepathstyle: true
    insecure: true
    bucketnames: loki
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: aws

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v13
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  max_look_back_period: 0s

query_range:
  parallelise_shardable_queries: true
  cache_results: true

compactor:
  working_directory: /loki/compactor
  shared_store: aws
  compaction_interval: 10m

limits_config:
  ingestion_rate_mb: 10
  max_concurrent_tail_requests: 20
